# Generated by Django 5.1.5 on 2025-02-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1),
        ),
    ]
