# Generated by Django 5.1.5 on 2025-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_vat_number_customer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='VAT_number',
            field=models.CharField(blank=True, default='No VAT number', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
