# Generated by Django 5.1.5 on 2025-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_vat_number_alter_customer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='VAT_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
