# Generated by Django 5.1.5 on 2025-02-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
